import { useEffect, useState } from 'react';
import { fallbackCatalog, type CatalogItem, type MarketplaceCatalog } from './catalog';
import { readPublicInventory } from './inventory';
import { version } from '../package.json';
import { artworkFor } from './artwork';

function availability(item: CatalogItem, readable: boolean, inventory: ReadonlyMap<string, bigint> | undefined) { if (!readable || !inventory) return 'Availability unreadable'; if (!item.assetId) return 'Not issued yet'; return (inventory.get(item.assetId) ?? 0n) > 0n ? 'Available in game wallet' : 'Not currently available'; }
function Artwork({ item, large = false }: { item: CatalogItem; large?: boolean }) { const size=large ? 104 : 72; const src=artworkFor(item.artwork); return <span className={`art ${large ? 'large ' : ''}art-${item.family.toLowerCase()}`} style={{width:size,height:size,overflow:'hidden'}}>{src ? <img src={src} alt={`${item.name} artwork`} style={{width:'100%',height:'100%',objectFit:'contain'}} /> : item.artwork}</span>; }
export function App() {
  const [catalog, setCatalog] = useState<MarketplaceCatalog>(fallbackCatalog);
  const [readable, setReadable] = useState(false);
  const [inventory, setInventory] = useState<ReadonlyMap<string, bigint>>();
  const [selected, setSelected] = useState<CatalogItem>();
  useEffect(() => { void fetch('/catalog.json', {cache:'no-store'}).then(async response => { if (!response.ok) throw Error(); const next=await response.json() as MarketplaceCatalog; if (next.version!==1 || !Array.isArray(next.items)) throw Error(); setCatalog(next); setReadable(true); }).catch(() => setReadable(false)); }, []);
  useEffect(() => { const controller=new AbortController(); setInventory(undefined); if (!catalog.gameWalletAddress || !catalog.items.every(item => item.assetId)) return () => controller.abort(); void readPublicInventory(catalog.gameWalletAddress, controller.signal).then(setInventory).catch(() => setInventory(undefined)); return () => controller.abort(); }, [catalog]);
  const sourceLabel = !readable ? 'Catalog data unavailable' : catalog.gameWalletAddress ? 'Read-only inventory source' : 'Wallet address not published yet';
  return <><div className="network-banner" role="status"><span>Signet</span><span>BIS v{version}</span></div><main className="marketplace-shell"><header><div><p className="eyebrow">BIS / STEALTH &amp; STEEL</p><h1>Marketplace</h1><p className="lede">Game equipment, discoverable before you play.</p></div><span className="public-tag">Public catalog</span></header><section className="wallet-strip" aria-label="Marketplace inventory"><span>Game wallet</span><code>{catalog.gameWalletAddress ?? 'Catalog address not published yet'}</code><strong>{sourceLabel}</strong></section><section><div className="section-heading"><div><p className="eyebrow">COLLECTION</p><h2>Stealth &amp; Steel equipment</h2></div><p>{catalog.items.length} items · No login required</p></div><div className="catalog-grid">{catalog.items.map(item => <button className="asset-card" key={item.id} onClick={() => setSelected(item)}><Artwork item={item} /><span className="family">{item.family} · Tier {item.tier}</span><strong>{item.name}</strong><small>{item.effect}</small><span className="availability">{availability(item, readable, inventory)}</span></button>)}</div></section>{selected && <div className="backdrop" role="presentation" onMouseDown={() => setSelected(undefined)}><article className="detail" role="dialog" aria-modal="true" aria-labelledby="item-title" onMouseDown={event => event.stopPropagation()}><button className="close" onClick={() => setSelected(undefined)} aria-label="Close item detail">×</button><Artwork item={selected} large /><p className="eyebrow">{selected.family} · TIER {selected.tier}</p><h2 id="item-title">{selected.name}</h2><p>{selected.effect}</p><dl><div><dt>Asset ID</dt><dd>{selected.assetId ?? 'Awaiting verified issuance'}</dd></div><div><dt>Status</dt><dd>{availability(selected, readable, inventory)}</dd></div></dl><div className="actions"><button disabled title="Trading arrives in the later Marketplace account flow">Buy</button><button disabled title="Trading arrives in the later Marketplace account flow">Sell</button></div><p className="truth">Trading is not available in this catalog release.</p></article></div>}</main></>;
}
