import { createContext } from '../../integration/src/core/context';
import { createBisUi } from '@bis/integration';
import '@bis/integration/style.css';

const host = document.getElementById('host')!;
const result = document.getElementById('result')!;
const tick = () => new Promise(resolve => setTimeout(resolve, 30));
const check = (condition: unknown, label: string) => { if (!condition) throw Error(label); };
let cleanup = () => {};
document.getElementById('run')!.onclick = async () => {
  cleanup(); result.textContent = 'Running';
  const account = {phrase:'isolated-placeholder',profileId:'1234567890abcdef'};
  let fail = false;
  let emptyBitcoin = true;
  const c = createContext({load:async()=>({account,generation:0}),save:async()=>{throw Error('Unexpected write');},reset:async()=>{},subscribe:()=>()=>{}}, undefined, async()=>account.profileId, undefined,
    async()=>{if(fail)throw Error('private');return emptyBitcoin ? {availableSats:289715,totalSats:289715,bitcoinSats:0,arkadeSats:289715} : {availableSats:800,totalSats:1500,bitcoinSats:500,arkadeSats:1000};});
  c.checkAccountTransfer=async()=>({status:'idle'});
  c.quoteAccountTransfer=async(amount=500,direction='to-arkade')=>({profileId:account.profileId,direction,amountSats:amount,feeSats:0,netSats:amount,maxSats:500,bitcoinAfterSats:500-amount,arkadeAfterSats:1000+amount,totalAfterSats:1500,expiresAt:Date.now()+60000,fingerprint:'test-only'});
  c.confirmAccountTransfer=async()=>{throw Error('Unexpected submission');};
  const ui = createBisUi(c);ui.mount(host);cleanup=()=>{ui.unmount();c.dispose();};
  const button = (name: string) => [...host.querySelectorAll('button')].find(b=>b.textContent===name)!;
  const value = (name: string) => (host.querySelector(`input[aria-label="${name}"]`) as HTMLInputElement)?.value;
  try {
    await c.ready();c.openAccountDialog();c.openAccountDetails();await tick();
    button('Bitcoin ↔ Arkade').click();await tick();
    const transferCard=host.querySelector('.bis-card')!;
    check(transferCard.scrollHeight<=transferCard.clientHeight,'Zero Bitcoin transfer fits without cropping or scrolling');
    check(host.querySelectorAll('.bis-balance-direction').length===1 && !!button('→'),'Single direction button starts forward');
    button('→').click();await tick();
    check(!!button('←'),'Click toggles reverse');
    button('←').click();await tick();
    check(!!button('→'),'Second click toggles forward');
    const notice=[...host.querySelectorAll('p')].find(p=>p.textContent?.startsWith('No Bitcoin'))!;
    check(notice.getBoundingClientRect().height<=parseFloat(getComputedStyle(notice).lineHeight)+1,'No Bitcoin notice fits on one line');
    check(button('Back').getBoundingClientRect().bottom<=transferCard.getBoundingClientRect().bottom,'Back is fully visible');
    button('Back').click();emptyBitcoin=false;await c.refreshBalance();await tick();
    check(value('Total balance')==='1,500 sats' && value('Bitcoin balance')==='500 sats' && value('Arkade balance')==='1,000 sats', 'Correct full balance split');
    check(!host.textContent?.includes('Available balance'), 'Old label removed');
    const labels=[...host.querySelectorAll('input[readonly]')];
    check(labels[0].getAttribute('aria-label')==='Total balance', 'Total first');
    check(labels[1].getBoundingClientRect().top===labels[2].getBoundingClientRect().top, 'Split balances on same row');
    check(button('Bitcoin ↔ Arkade').nextElementSibling===button('Recovery Phrase'),'Transfer before Recovery Phrase');
    button('Bitcoin ↔ Arkade').click();await tick();
    check(host.querySelector('h2')?.textContent==='Account Transfer','Transfer title');
    check(button('Review Transfer').disabled && !button('Max').disabled,'Initial zero and forward Max enabled');
    button('Max').click();await tick();
    button('Review Transfer').click();await tick();
    check(host.textContent?.includes('500 sats') && host.textContent.includes('After transfer (estimate)'),'Real quote fields rendered');
    check(!button('Confirm Transfer').disabled,'Reviewed forward quote enables explicit confirmation');
    button('Back').click();await tick();
    (host.querySelector('[aria-label="Increase amount"]') as HTMLButtonElement).click();await tick();
    check(!button('Review Transfer').disabled,'Positive amount review');
    button('→').click();await tick();
    check(!!button('←') && !button('→'),'Direction toggled to reverse');
    check(transferCard.scrollHeight<=transferCard.clientHeight,'Reverse transfer form fits without cropping or scrolling');
    button('Review Transfer').click();await tick();
    check(host.textContent?.includes('Review: Arkade → Bitcoin') && host.textContent.includes('501 sats'),'Reverse review');
    check(!button('Confirm Transfer').disabled && host.textContent?.includes('After transfer (estimate)'),'Reviewed reverse quote enables explicit confirmation');
    button('Back').click();await tick();check(!!button('←'),'Back retains direction');
    button('Back').click();await tick();check(host.querySelector('h2')?.textContent==='Account Details','Back to Details');
    button('Bitcoin ↔ Arkade').click();await tick();check(button('Review Transfer').disabled,'Reopen resets amount');
    button('Back').click();await tick();fail=true;await c.refreshBalance();await tick();
    check(value('Total balance')==='' && value('Arkade balance')==='' && !!host.querySelector('.bis-pending-dialog'),'Failed refresh stays covered');
    check([...host.querySelectorAll('button[aria-label^="Copy"]')].every(b=>(b as HTMLButtonElement).disabled),'Failed copy disabled');
    fail=false;button('OK').click();await tick();c.openAccountDetails();await tick();
    button('Bitcoin ↔ Arkade').click();await tick();button('Max').click();await tick();button('Review Transfer').click();await tick();
    c.checkAccountTransfer=async()=>{throw Error('private status failure');};
    button('Confirm Transfer').click();await tick();
    check(!host.textContent?.includes('Transfer pending') && !host.textContent?.includes('Log Out and Reset are blocked'),'Rejected confirmation without a record must not invent a pending operation');
    check(button('Confirm Transfer')?.disabled || button('Review Transfer')?.disabled,'Unknown status blocks another confirmation until checked');
    c.checkAccountTransfer=async()=>({status:'pending',phase:'registered',direction:'to-bitcoin',amountSats:1000,operationId:'test-operation',intentId:'test-intent',verification:'unavailable'});
    button('OK').click();await tick();button('Bitcoin ↔ Arkade').click();await tick();
    check(host.textContent?.includes('A pending transfer is blocking new transfers.') && !host.textContent?.includes('test-intent'),'Pending notice directs to Activity without recovery details');
    check(!!button('←') && button('Review Transfer').disabled,'Pending reverse operation is preserved');
    c.checkAccountTransfer=async()=>({status:'succeeded',direction:'to-bitcoin',amountSats:1000,operationId:'test-operation',commitmentTxid:'b'.repeat(64),verification:'live'});
    button('OK').click();await tick();button('Bitcoin ↔ Arkade').click();await tick();
    check(!host.querySelector('.bis-pending-dialog') && !host.textContent?.includes('Transfer verified') && !host.textContent?.includes('Log Out and Reset are blocked'),'Verified completion reveals prepared UI without a banner');
    const card=host.querySelector('.bis-card')!;check(card.scrollWidth<=card.clientWidth,'No horizontal overflow');
    button('Back').click();emptyBitcoin=true;await c.refreshBalance();c.checkAccountTransfer=async()=>({status:'idle'});await tick();
    button('Bitcoin ↔ Arkade').click();await tick();
    result.textContent='PASS: zero-Bitcoin layout fits 360 × 640, single-line notice, single direction button toggles both ways, visible Back, balance split, quote review, pending dialog, final error dismissal and completion. Isolated test doubles; no live submission.';
  } catch(error) {result.textContent=`FAIL: ${error instanceof Error ? error.message : 'transfer checks'}`;}
};
