import { createContext } from '../../integration/src/core/context';
import { PendingTransferConfirmationError } from '../../integration/src/core/boarding-record';
import { createBisUi } from '@bis/integration';
import '@bis/integration/style.css';

const host = document.getElementById('host')!;
const result = document.getElementById('result')!;
const tick = () => new Promise(resolve => setTimeout(resolve, 30));
const check = (condition: unknown, label: string) => { if (!condition) throw Error(label); };
let cleanup = () => {};
document.getElementById('run')!.onclick = async () => {
  cleanup(); result.textContent = 'Running';
  const account = {phrase:'isolated-placeholder',profileId:'1234567890abcdef'};
  let fail = false, quoteLifetime=60000;
  let emptyBitcoin = true;
  const c = createContext({load:async()=>({account,generation:0}),save:async()=>{throw Error('Unexpected write');},reset:async()=>{},subscribe:()=>()=>{}}, undefined, async()=>account.profileId, undefined,
    async()=>{if(fail)throw Error('private');return emptyBitcoin ? {availableSats:289715,totalSats:289715,bitcoinSats:0,arkadeSats:289715} : {availableSats:800,totalSats:1500,bitcoinSats:500,arkadeSats:1000};});
  c.getPendingAccountTransfers=()=>[];
  c.checkAccountTransfer=async()=>({status:'idle'});
  c.quoteAccountTransfer=async(amount=500,direction='to-arkade')=>({profileId:account.profileId,direction,amountSats:amount,feeSats:0,netSats:amount,maxSats:500,bitcoinAfterSats:500-amount,arkadeAfterSats:1000+amount,totalAfterSats:1500,expiresAt:Date.now()+quoteLifetime,fingerprint:'test-only'});
  c.confirmAccountTransfer=async()=>{throw Error('Unexpected submission');};
  const ui = createBisUi(c);ui.mount(host);cleanup=()=>{ui.unmount();c.dispose();};
  const button = (name: string) => [...host.querySelectorAll('button')].find(b=>b.textContent===name)!;
  const value = (name: string) => (host.querySelector(`input[aria-label="${name}"]`) as HTMLInputElement)?.value;
  try {
    await c.ready();c.openAccountDialog();c.openAccountDetails();await tick();
    c.openAccountTransfer();await tick();
    const transferCard=host.querySelector('.bis-card')!;
    check(transferCard.scrollHeight<=transferCard.clientHeight,'Zero Bitcoin transfer fits without cropping or scrolling');
    check(host.querySelectorAll('.bis-balance-direction').length===1 && !!button('→'),'Single direction button starts forward');
    button('→').click();await tick();
    check(!!button('←'),'Click toggles reverse');
    button('←').click();await tick();
    check(!!button('→'),'Second click toggles forward');
    const notice=[...host.querySelectorAll('p')].find(p=>p.textContent?.startsWith('No Bitcoin'))!;
    const noticeText=document.createRange();noticeText.selectNodeContents(notice);
    check(noticeText.getBoundingClientRect().height<=parseFloat(getComputedStyle(notice).lineHeight)+1,'No Bitcoin notice text fits on one line');
    check(button('Back').getBoundingClientRect().bottom<=transferCard.getBoundingClientRect().bottom,'Back is fully visible');
    button('Back').click();emptyBitcoin=false;await c.refreshBalance();await tick();
    check(value('Total balance')==='1,500 sats' && value('Bitcoin balance')==='500 sats' && value('Arkade balance')==='1,000 sats', 'Correct full balance split');
    check(!host.textContent?.includes('Available balance'), 'Old label removed');
    const labels=[...host.querySelectorAll('input[readonly]')];
    check(labels[0].getAttribute('aria-label')==='Total balance', 'Total first');
    check(labels[1].getBoundingClientRect().top===labels[2].getBoundingClientRect().top, 'Split balances on same row');
    check(!!button('Get Recovery Phrase'),'Recovery action on Balance');
    c.openAccountTransfer();await tick();
    check(host.querySelector('h2')?.textContent==='Account Transfer','Transfer title');
    check(button('Review Transfer').disabled && !button('Max').disabled,'Initial zero and forward Max enabled');
    button('Max').click();await tick();
    button('Review Transfer').click();await tick();
    check(host.textContent?.includes('500 sats') && host.textContent.includes('After transfer (estimate)'),'Real quote fields rendered');
    check(!button('Confirm Transfer').disabled,'Reviewed forward quote enables explicit confirmation');
    button('Back').click();await tick();quoteLifetime=80;button('Review Transfer').click();await tick();
    // Wait for the expiry effect to render, rather than assuming three 30ms ticks suffice.
    const expiryDeadline = Date.now() + 1000;
    while (!button('Confirm Transfer').disabled && Date.now() < expiryDeadline) await tick();
    check(button('Confirm Transfer').disabled,'Expired transfer cannot submit');
    button('Back').click();await tick();quoteLifetime=60000;button('Review Transfer').click();await tick();check(!button('Confirm Transfer').disabled,'Fresh transfer quote enables confirmation');
    button('Back').click();await tick();
    (host.querySelector('[aria-label="Increase amount"]') as HTMLButtonElement).click();await tick();
    check(!button('Review Transfer').disabled,'Positive amount review');
    button('→').click();await tick();
    check(!!button('←') && !button('→'),'Direction toggled to reverse');
    check(transferCard.scrollHeight<=transferCard.clientHeight,'Reverse transfer form fits without cropping or scrolling');
    button('Review Transfer').click();await tick();
    check(host.textContent?.includes('Review: Arkade → Bitcoin') && host.textContent.includes('501 sats'),'Reverse review');
    check(!button('Confirm Transfer').disabled && host.textContent?.includes('After transfer (estimate)'),'Reviewed reverse quote enables explicit confirmation');
    button('Back').click();await tick();check(!!button('←'),'Back retains direction');
    button('Back').click();await tick();check(host.querySelector('h2')?.textContent==='Balance','Back to Details');
    c.openAccountTransfer();await tick();check(button('Review Transfer').disabled,'Reopen resets amount');
    button('Back').click();await tick();fail=true;await c.refreshBalance();await tick();
    check(value('Total balance')==='' && value('Arkade balance')==='' && !!host.querySelector('.bis-pending-dialog'),'Failed refresh stays covered');
    check([...host.querySelectorAll('button[aria-label^="Copy"]')].every(b=>(b as HTMLButtonElement).disabled),'Failed copy disabled');
    fail=false;button('OK').click();await tick();c.openAccountDetails();await tick();
    c.openAccountTransfer();await tick();button('Max').click();await tick();button('Review Transfer').click();await tick();
    c.checkAccountTransfer=async()=>{throw Error('private status failure');};
    button('Confirm Transfer').click();await tick();
    check(!host.textContent?.includes('Transfer pending') && !host.textContent?.includes('Log Out and Reset are blocked'),'Rejected confirmation without a record must not invent a pending operation');
    check(button('Confirm Transfer')?.disabled || button('Review Transfer')?.disabled,'Unknown status blocks another confirmation until checked');
    c.checkAccountTransfer=async()=>({status:'pending',phase:'registered',direction:'to-bitcoin',amountSats:1000,operationId:'test-operation',intentId:'test-intent',verification:'unavailable'});
    button('OK').click();await tick();c.openAccountTransfer();await tick();
    check(host.textContent?.includes('Check Transactions for updates on pending transfers.') && !host.textContent?.includes('test-intent'),'Pending notice directs to Transactions');
    check(!host.querySelector<HTMLButtonElement>('.bis-balance-direction')!.disabled,'Pending operation leaves either direction available');
    c.getPendingAccountTransfers=()=>[{status:'pending',amountSats:1000,operationId:'test-operation',direction:'to-bitcoin'}];
    button('Max').click();await tick();button('Review Transfer').click();await tick();
    check(host.textContent?.includes('You already have a transfer of 1,000 sats pending. Are you sure you want to send another?'),'Forward attempt warns about pending reverse transfer');
    button('Cancel').click();await tick();check(!button('Confirm Transfer'),'Cancel does not review or submit');
    host.querySelector<HTMLButtonElement>('.bis-balance-direction')!.click();await tick();button('Review Transfer').click();await tick();
    check(!!button('Yes') && !!button('Cancel'),'Reverse attempt warns too');
    button('Yes').click();await tick();check(!!button('Confirm Transfer'),'Yes permits a fresh review');
    c.getPendingAccountTransfers=()=>[{status:'pending',amountSats:1000,operationId:'test-operation'},{status:'pending',amountSats:500,operationId:'other-tab-operation'}];
    c.confirmAccountTransfer=async()=>{throw new PendingTransferConfirmationError('Pending transfers changed.');};
    button('Confirm Transfer').click();await tick();
    check(host.textContent?.includes('1,500 sats pending') && !!button('Yes'),'A new pending transfer at confirmation asks again');
    button('Yes').click();await tick();check(!!button('Confirm Transfer'),'Changed pending set gets a fresh review after Yes');
    let submissions=0;
    c.confirmAccountTransfer=async(_quote,ids)=>{check(ids?.includes('test-operation')&&ids.includes('other-tab-operation'),'All pending acknowledgements accompany submission');submissions++;return {status:'pending',phase:'registered',operationId:'second-operation',amountSats:500,direction:'to-bitcoin'};};
    button('Confirm Transfer').click();await tick();
    check(submissions===1 && host.textContent?.includes('Transfer pending.') && host.textContent.includes('You can view progress in Transactions.'),'Registered transfer shows pending acknowledgement');
    check(!host.textContent?.includes('Operation unavailable'),'Pending is not an operation failure');
    button('OK').click();await tick();
    c.getPendingAccountTransfers=()=>[];
    c.checkAccountTransfer=async()=>({status:'succeeded',direction:'to-bitcoin',amountSats:1000,operationId:'test-operation',commitmentTxid:'b'.repeat(64),verification:'live'});
    c.openAccountTransfer();await tick();
    check(!host.querySelector('.bis-pending-dialog') && !host.textContent?.includes('Transfer verified') && !host.textContent?.includes('Log Out and Reset are blocked'),'Verified completion reveals prepared UI without a banner');
    const card=host.querySelector('.bis-card')!;check(card.scrollWidth<=card.clientWidth,'No horizontal overflow');
    button('Back').click();emptyBitcoin=true;await c.refreshBalance();c.checkAccountTransfer=async()=>({status:'idle'});await tick();
    c.openAccountTransfer();await tick();
    // The adapter tests exercise SDK asset selection; here verify the UI uses its
    // withdrawable Max and retained-change projections without replacing them.
    c.quoteAccountTransfer=async(amount=289385,direction='to-bitcoin')=>({profileId:account.profileId,direction,amountSats:amount,feeSats:0,netSats:amount,maxSats:289385,inputSats:289715,bitcoinAfterSats:amount,arkadeAfterSats:289715-amount,totalAfterSats:289715,expiresAt:Date.now()+60000,fingerprint:'asset-test-only'});
    button('→').click();await tick();button('Max').click();await tick();
    check((host.querySelector('input:not([readonly])') as HTMLInputElement)?.value==='289385','Max reserves 330 sats for assets');
    button('Review Transfer').click();await tick();
    check(host.textContent?.includes('289,385 sats') && host.textContent.includes('330 sats'),'Asset-preserving reverse quote renders withdrawal and retained Arkade balance');
    check(!button('Confirm Transfer').disabled,'Asset-preserving review reaches explicit confirmation');
    check(card.scrollWidth<=card.clientWidth,'Asset review has no horizontal overflow');
    result.textContent='PASS: transfer layout, directions, review, expiry and recovery checks; asset-preserving Max and 330-sat Arkade change rendered. Isolated test doubles; no live submission.';
  } catch(error) {result.textContent=`FAIL: ${error instanceof Error ? error.message : 'transfer checks'}`;}
};
