import assert from 'node:assert/strict';
import test from 'node:test';
import {createContext,getControls} from '../../src/client/state-layer-core/context.ts';
import {createLtoService} from '../../src/client/state-layer-core/lto-service.ts';
import {operatorFor} from '../../src/client/wallet-layer-arkade/account.ts';
const tick=()=>new Promise(r=>setImmediate(r));
test('passive sharing normalizes filters, preserves full coverage and recomputes expiry without financial work',async t=>{
 const original=Object.getOwnPropertyDescriptor(globalThis,'localStorage');
 Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>null}});
 globalThis.requestIdleCallback=()=>1;globalThis.cancelIdleCallback=()=>{};
 const account={profileId:'player',phrase:'fixture-only'};
 const c=createContext({load:async()=>({account,generation:0}),subscribe:()=>()=>{}},undefined,async()=>account.profileId);
 t.after(()=>{c.dispose();delete globalThis.requestIdleCallback;delete globalThis.cancelIdleCallback;if(original)Object.defineProperty(globalThis,'localStorage',original);else delete globalThis.localStorage;});
 const now=Date.now();
 const record=(id,network,financial='funded')=>({version:1,type:'lto',id,scope:{playerId:'player',gameId:'game',operator:operatorFor(network),network,exclusivityKey:id},sessionId:id,purpose:'reward',hostReference:id,amountSats:100,startedAt:now-100,expiresAt:now+1000,financial,operation:{id:'op-'+id,kind:'fund',submission:'confirmed'}});
 const rows=[record('current','signet'),record('resolved','signet','claimed'),record('other','mutinynet')];
 const document={ledger:{contracts:rows,attempts:[]},recovery:Object.fromEntries(rows.map(r=>[r.id,{}]))};
 let calls=0,release;let gate=new Promise(r=>release=r);
 const forbidden=async()=>assert.fail('Passive preparation reached a financial adapter');
 const lto=createLtoService({context:c,gameWallet:{getState:()=>({status:'ready',profileId:'game'})}},{storage:{load:async()=>{calls++;await gate;return document;}},playerStorage:{load:forbidden},gameStorage:{load:forbidden},prepare:forbidden,submit:forbidden,reconcile:forbidden,resume:forbidden,poll:false});
 t.after(()=>lto.dispose({preserveContracts:true}));await c.readyAsync();
 const a=c.checkContractsAsync({includeResolved:true,includeOtherNetworks:true});
 const b=c.checkContractsAsync({includeOtherNetworks:true,includeResolved:true});
 const force=c.checkContractsAsync({includeResolved:true,includeOtherNetworks:true},true);
 await tick();assert.equal(calls,1);release();
 assert.equal((await a).contracts.length,3);await b;await force;assert.equal(calls,1);
 assert.equal((await c.checkContractsAsync({hostReference:'current'})).contracts.length,1);assert.equal(calls,2);
 assert.equal((await c.checkContractsAsync({includeResolved:true,includeOtherNetworks:true})).contracts.length,3);assert.equal(calls,2);
 const realNow=Date.now;t.mock.method(Date,'now',()=>now+2000);
 const expired=(await c.checkContractsAsync({includeResolved:true,includeOtherNetworks:true})).contracts.find(r=>r.id==='current');
 assert.equal(expired.eligibility,'expired');assert.equal(expired.canClaim,false);assert.equal(calls,2);t.mock.restoreAll();assert.ok(realNow()>0);
 await c.checkContractsAsync({includeResolved:true,includeOtherNetworks:true},true);assert.equal(calls,3);
 assert.equal(getControls(c).toasts.getSnapshot(),null);assert.equal(c.getState().view,'empty');
});
