import { createContext } from '../../integration/src/core/context';
import { createBisUi } from '@bis/integration';
import { formatTransactionDetail, formatTransactionSummary, type BisTransaction } from '../../integration/src/core/activity';
import '@bis/integration/style.css';
const host=document.getElementById('host')!,result=document.getElementById('result')!;
const tick=()=>new Promise(r=>setTimeout(r,0));
const check=(ok:unknown,label:string)=>{if(!ok)throw Error(label);};
const wait=async(test:()=>boolean)=>{const end=Date.now()+2500;while(!test()){if(Date.now()>end)throw Error('UI update timed out');await tick();}};
let cleanup=()=>{};
document.getElementById('run')!.onclick=async()=>{
  cleanup();result.textContent='Running';
  let copied='',copyFail=false,rejectRead:(error:Error)=>void=()=>{};
  const rows: readonly BisTransaction[]=Array.from({length:24},(_,i)=>({id:String(i),amountSats:100+i,direction:i%2?'Outgoing':'Incoming',status:i===0?'Pending':'Confirmed',identifier:'a'.repeat(64)+':'+i,bitcoin:{txid:'a'.repeat(64),confirmations:i===0?0:3},createdAt:24-i,...(i===0?{kind:'Asset transfer',assets:[{assetId:'fixture-asset',quantity:'9007199254740993'}]}:{})}));
  const original=Object.getOwnPropertyDescriptor(navigator,'clipboard');
  Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text:string)=>{if(copyFail)throw Error('denied');copied=text;}}});
  let data=rows;
  const account={phrase:'isolated-placeholder',profileId:'1234567890abcdef'};
  const c=createContext({load:async()=>({account,generation:0}),save:async()=>{throw Error('unexpected write');},reset:async()=>{},subscribe:()=>()=>{}},undefined,async()=>account.profileId,undefined,undefined,undefined,undefined,async(_,signal,publish)=>{
    await tick();if(signal.aborted)return;publish(data);await new Promise<void>((resolve,reject)=>{rejectRead=reject;signal.addEventListener('abort',()=>resolve(),{once:true});});
  });
  const ui=createBisUi(c);ui.mount(host);
  cleanup=()=>{ui.unmount();c.dispose();if(original)Object.defineProperty(navigator,'clipboard',original);else Reflect.deleteProperty(navigator,'clipboard');};
  try{
    await c.ready();c.openAccountDialog();await tick();
    const buttons=[...host.querySelectorAll('button')];const details=buttons.findIndex(b=>b.textContent?.includes('Account Details'));
    check(buttons[details+1]?.textContent?.includes('Account Activity'),'menu order');buttons[details+1].click();
    await wait(()=>host.querySelectorAll('.bis-transaction-row').length===24);
    check(!host.querySelector('textarea'),'list instead of text area');
    check(host.querySelector('.bis-transaction-row')?.textContent===formatTransactionSummary(rows[0]),'compact row text');
    const activityHeight=host.querySelector('.bis-card')!.getBoundingClientRect().height;
    check(activityHeight===480,'fixed activity height');
    const list=host.querySelector<HTMLElement>('.bis-transaction-list')!;
    check(getComputedStyle(list).overflowY==='scroll' && getComputedStyle(list).scrollbarWidth!=='none','always visible list scrollbar');
    check(list.scrollHeight>list.clientHeight,'long list scrolls internally');
    check(getComputedStyle(host.querySelector('.bis-transaction-row')!).whiteSpace==='nowrap','rows never wrap');
    check(!list.textContent?.includes('fixture-asset'),'asset metadata only in details');
    host.querySelector<HTMLButtonElement>('.bis-transaction-row')!.click();
    await tick();
    check(!!host.querySelector('textarea'),'first click opens transaction details');
    await wait(()=>host.querySelector('textarea')?.value===formatTransactionDetail(rows[0]));
    check(host.querySelector('textarea')?.value.includes('9007199254740993 base units'),'exact asset quantity');
    check(host.querySelector('textarea')?.value.includes('Confirmations: 0'),'confirmation count in detail');
    check(host.querySelector('textarea')?.value.includes('Waiting for the first block'),'pending wait guidance');
    check(host.querySelector('textarea')?.value.includes('Timestamp (UTC): 1970-01-01 00:00:00'),'recorded timestamp in detail');
    check(host.querySelectorAll('textarea').length===1,'one text area');
    const explorer=[...host.querySelectorAll('button')].find(b=>b.textContent==='Open explorer');
    check(explorer && !explorer.disabled,'transaction detail exposes enabled explorer button');
    check(host.querySelector('.bis-card')!.getBoundingClientRect().height===activityHeight,'detail matches activity height');
    await wait(()=>host.querySelector('h2')?.textContent==='Transaction Detail');
    check(document.activeElement!==host.querySelector('textarea'),'detail field is not automatically focused');
    check(host.textContent?.includes('Account ID:'),'account identifier');
    const copy=host.querySelector<HTMLButtonElement>('[aria-label="Copy Transaction"]')!;
    copy.click();await wait(()=>copied===formatTransactionDetail(rows[0]));await tick();check(!host.textContent?.includes('Transaction copied.'),'no separate copy success message');
    copyFail=true;copy.click();await wait(()=>host.textContent?.includes('Could not copy.')===true);
    check(host.querySelector('.bis-card')!.getBoundingClientRect().height===activityHeight,'copy feedback does not resize dialog');
    const card=host.querySelector('.bis-card')!;check(card.scrollWidth<=card.clientWidth,'no horizontal card overflow');
    const back=[...host.querySelectorAll('button')].filter(b=>b.textContent==='Back');check(back.length===1,'single Back');back[0].click();
    await wait(()=>host.querySelectorAll('.bis-transaction-row').length===24);
    check(host.querySelector('.bis-transaction-row')?.getAttribute('aria-pressed')==='true','Back retains selection');
    rejectRead(Error('private failure'));await wait(()=>c.getState().activity.status==='unavailable');await tick();
    check(!host.querySelector('.bis-transaction-row') && !host.querySelector('textarea'),'clear stale text');
    data=[];void c.refreshActivity();await wait(()=>host.textContent?.includes('No transactions found.')===true);
    check(host.querySelector('.bis-card')!.getBoundingClientRect().height===activityHeight,'empty list keeps dialog height');
    check(getComputedStyle(host.querySelector('.bis-transaction-list')!).overflowY==='scroll','empty list retains scrollbar');
    c.closeAccount();await tick();check(!host.querySelector('textarea'),'Back to menu');
    data=rows;c.openAccountActivity();await wait(()=>host.querySelectorAll('.bis-transaction-row').length===24);
    check(host.querySelectorAll('[aria-pressed="true"]').length===0,'reopen clears selection');
    result.textContent='PASS: compact single-line rows, fixed height, persistent scrollbar, selection/open/Back, detailed copy, clipboard failure, empty/unavailable/retry, reopen, 360px layout. Fixtures only.';
  }catch(error){result.textContent='FAIL: '+(error instanceof Error?error.message:'checks');}
};
window.addEventListener('pagehide',()=>cleanup());
