export const layout=`
<header><span class="brand">ARKADE OS / EXPERIMENT 01</span><span class="pill">SIGNET · TEST SATS</span></header>
<h1>Bitcoin in.<br><span>Half to Arkade.</span></h1>
<p class="intro">Six steps. CPU handles the network work. USER handles funding and authorizes the transfer.</p>
<p class="muted">Times below are rough estimates, not deadlines. Faucet queues and network conditions can take longer.</p>
<section class="balances"><article><label>Bitcoin</label><strong id="bitcoin">—</strong><small>Onchain sats</small></article><div class="arrow">→</div><article><label>Arkade</label><strong id="arkade">—</strong><small id="available">Spendable sats: —</small></article></section>
<section class="panel"><div class="step">STEP 1 <span class="owner">CPU</span><span class="estimate">~10 seconds</span></div><h2>Create account</h2><button id="create" class="primary" disabled>Create</button><p id="account-status" class="muted" role="status">Restoring saved account…</p><h3 id="recovery-label">Seed phrase</h3><p id="recovery-info" class="muted">New accounts have a 12-word recovery phrase for reuse in development.</p><button id="reveal-recovery" disabled>Reveal recovery details</button><div id="recovery-visible" hidden><textarea id="recovery-value" aria-label="Account recovery secret" readonly spellcheck="false" autocomplete="off" rows="3"></textarea><button id="copy-recovery">Copy recovery details</button></div><p id="recovery-feedback" class="muted" role="status"></p><p class="muted">Anyone with these recovery details can control this wallet. Store them privately; do not paste them into chat. Hidden again after 60 seconds or when you leave the tab.</p><p class="muted">Saved in this browser. Refresh keeps the same account. Recreate starts another account; previous encrypted account data is retained.</p></section>
<section class="panel"><div class="step">STEP 2 <span class="owner user">USER</span><span class="estimate">~1–5 minutes</span></div><h2>Fund the account</h2><label for="address">Bitcoin boarding address</label><div class="address"><input id="address" readonly value="No account created yet"><button id="copy" disabled>Copy</button></div><p id="copied" role="status"></p><button id="faucet" class="primary" disabled>Open faucet and fund</button></section>
<section class="panel"><div class="step">STEP 3 <span class="owner">CPU</span><span class="estimate">~10–60 minutes</span></div><h2>Wait for incoming Bitcoin</h2><p id="incoming-status" role="status">Create an account to start watching for incoming transactions.</p><div id="incoming-rows"></div><p class="muted" id="incoming-checked">No transaction check completed yet.</p><a id="address-explorer" target="_blank" rel="noopener noreferrer">View address on the Signet explorer ↗</a></section>
<section class="panel"><div class="step">STEP 4 <span class="owner user">USER</span><span class="estimate">~10 seconds</span></div><h2>Onboard 50%</h2><p id="eligibility" role="status">Available after incoming Bitcoin is confirmed.</p><button id="onboard" class="primary" disabled>Onboard 50%</button><p class="muted">Half arrives in Arkade, rounded down. Any verified fees come from the Bitcoin remainder.</p></section>
<section class="panel"><div class="step">STEP 5 <span class="owner">CPU</span><span class="estimate">~10–60 minutes</span></div><h2>Track Bitcoin → Arkade</h2><div id="status" role="status" aria-live="polite">No onboarding transfer submitted.</div><p id="error" role="alert"></p><dl><dt>Target in Arkade</dt><dd id="target">—</dd><dt>Verified fee</dt><dd id="fee">—</dd><dt>Bitcoin change</dt><dd id="change">—</dd><dt>Intent ID</dt><dd id="intent">—</dd><dt>Commitment</dt><dd id="commitment">—</dd></dl></section>
<section class="panel" id="ready-panel"><div class="step">STEP 6 <span class="owner">CPU</span><span class="estimate">~5–15 seconds after settlement</span></div><h2>Confirm usable Arkade funds are ready</h2><p id="usable" role="status">Not ready yet. CPU will verify spendable Arkade funds after the transfer settles.</p></section>
<div class="refresh-bar"><button id="refresh" disabled>Refresh status</button><span class="muted">Last fresh check: <span id="checked">—</span></span></div>
<footer>Standalone · <span id="sdk"></span> · Keep this tab open during signing.</footer>`;
